spring:
  datasource:
    driver-class-name: org.h2.Driver
    url : jdbc:h2:tcp://localhost/~/testmsa
    username: sa
    password: '{cipher}4c023da2b842565f11e61b3d2cc201fe3604453222d6f7e0dc6e6c8b3cde3432' #μ•”νΈν™”!
    
token:
  expiration_time: 8640000000 # 1 day
  secret: user_token_default

gateway:
  ip: 121.146.60.50
